sudo: true
dist: trusty

before_install:
  - openssl aes-256-cbc -K $encrypted_b7cdc4440a66_key -iv $encrypted_b7cdc4440a66_iv -in deploy_key.enc -out ./deploy_key -d
  - chmod 0400 deploy_key

install:
  - sudo apt-get install hugo

before_script:
  - echo -e "Host github.com\n  IdentityFile ${TRAVIS_BUILD_DIR}/deploy_key\n" > ~/.ssh/config
  - echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ~/.ssh/known_hosts

script:
  - build/publish.sh

env:
  global:
  - GIT_NAME=azriel91
  - GIT_EMAIL=azriel91@gmail.com
