baseURL = "https://azriel.im/will"
languageCode = "en-us"
title = "Will"
theme = ["hugo-easy-gallery", "beautifulhugo"]
enableEmoji = true
canonifyURLs = true
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
summaryLength = 44
pygmentsCodefences = true
pygmentsStyle = "fruity"

googleAnalytics = "UA-122495090-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  post = "/:year/:month/:day/:slug/"
  page = "/:slug/"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -110

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = -120

[[menu.main]]
  name = "Categories"
  url = "/categories"
  weight = -130

[Params]
  homeTitle = "Will"
  subtitle = "2.5D Action/Adventure Game"
  logo = "media/will_logo.png"
  favicon = "media/favicon.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = true
  comments = true
  readingTime = false
  useHLJS = false
  socialShare = false
  gcse = "001170321302850785855:ikbend5xmbo" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Azriel Hoh"
  website = "https://azriel.im/"
  email = "mail@azriel.im"
  github = "azriel91"
  # twitter = "im_azriel"
  # reddit = "azrielh"
  # youtube = "user/azriel91"
  # itchio = "azriel91"

[outputs]
  post = ["HTML"]
