baseURL = "https://azriel.im/"
languageCode = "en-us"
title = "Will"
theme = ["natrium", "hugo-easy-gallery"]

enableEmoji = true
# googleAnalytics = "UA-122495090-1"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  post = "/:slug/"
  page = "/:slug/"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = -110

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = -120

[[menu.main]]
  name = "Categories"
  url = "/categories"
  weight = -130

[params]
  description = ""

  [params.logo]
  url = "will_logo.png"
  width = 50
  height = 50
  alt = "Will"

[outputs]
  post = ["HTML"]
